#!/usr/bin/env python
# -*- coding=utf-8 -*-

# Author: Ryan Henrichson
# URL: https://github.com/orcephrye/PyController


import sys, os
import PyController
from PyController.PyController import main

if __name__ == '__main__':
    main(install_dir=os.path.realpath(os.path.dirname(PyController.__file__)))
    sys.exit(0)
